export const SERVICES = [
  {
    label: "函数计算 FC",
    value: "函数计算 FC",
    url: "https://fcnext.console.aliyun.com",
    product: "fc",
  },
  {
    label: "对象存储 OSS",
    value: "对象存储 OSS",
    url: "https://oss.console.aliyun.com",
    product: "oss",
  },
  {
    label: "日志服务 SLS",
    value: "日志服务 SLS",
    url: "https://sls.console.aliyun.com",
    product: "sls",
  },
  {
    label: "文件存储 NAS",
    value: "文件存储 NAS",
    url: "https://nasnext.console.aliyun.com",
    product: "nas",
  },
  {
    label: "容器镜像服务 CR",
    value: "容器镜像服务 CR",
    url: "https://cr.console.aliyun.com",
    product: "acr",
  },
  {
    label: "专有网络 VPC",
    value: "专有网络 VPC",
    url: "https://vpc.console.aliyun.com",
    product: "vpc",
  },
  {
    label: "事件总线 EventBridge",
    value: "事件总线 EventBridge",
    url: "https://eventbridge.console.aliyun.com",
    product: "eventbridge",
  },
  {
    label: "表格存储 Tablestore",
    value: "表格存储 Tablestore",
    url: "https://otsnext.console.aliyun.com",
    product: "ots",
  },
  {
    label: "Serverless应用引擎 SAE",
    value: "Serverless应用引擎 SAE",
    url: "https://sae.console.aliyun.com",
    product: "sae",
  },
  {
    label: "CDN",
    value: "CDN",
    url: "https://cdn.console.aliyun.com",
    product: "cdn",
  },
  {
    label: "云数据库RDS MySQL 版",
    value: "云数据库RDS MySQL 版",
    url: "https://rdsnext.console.aliyun.com",
    product: "rds",
  },
  {
    label: "视频点播",
    value: "视频点播",
    url: "https://vod.console.aliyun.com",
    product: "vod",
  },
  {
    label: "视频直播",
    value: "视频直播",
    url: "https://live.console.aliyun.com",
    product: "live",
  },
  {
    label: "智能媒体服务",
    value: "智能媒体服务",
    url: "https://ice.console.aliyun.com",
    product: "ice",
  },
  {
    label: "媒体处理",
    value: "媒体处理",
    url: "https://mps.console.aliyun.com",
    product: "mts",
  },
  {
    label: "低代码音视频工厂",
    value: "低代码音视频工厂",
    url: "https://imp.console.aliyun.com",
    product: "imp",
  },
  {
    label: "音视频通信 RTC",
    value: "音视频通信 RTC",
    url: "https://rtc.console.aliyun.com",
    product: "rtc",
  },
];
